### ISSUE TITLE
Unrecognized URI - Can't Find Referenced JSON Schema File

### ISSUE THREAD

**Issue by sdoca** [mulesoft-labs/raml-for-jax-rs#202]
This may be related to https://github.com/mulesoft/raml-for-jax-rs/issues/97 but that says the issue was solved/released in version 1.3.4 which is what I am using.  I have a raml file which imports a book schema file which in turn references an author schema file.  All three files live in the same directory.  My raml looks like this:

```
#%RAML 0.8

---
title: book
version: 1.0
mediaType: application/json
schemas:
  - book:  !include book.json

/books:
  /{bookTitle}:
    get:
      description: Retrieve a specific book title
      queryParameters:
        author:
          displayName: Author
          type: string
          description: An author's full name
          example: Mary Roach
          required: false
        title:
          displayName: Title
          type: string
          description: Title of the book
          example: 1984
          required: false
        genre:
          displayName: Genre
          type: string
          description: Genre
          example: Mystery
          required: false
        isbn:
          displayName: ISBN
          type: string
          minLength: 10
          example: 0321736079
          required: false
      responses:
        200:
          body:
            schema: book
```

The book.json looks like this:

```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "book",
    "type": "object",
    "properties": {
        "isbn": {
            "description": "ISBN",
            "type": "string"
        },
        "title": {
            "description": "title",
            "type": "string"
        },
        "genre": {
            "description": "genre",
            "type": "string"
        },
        "author": {
            "$ref": "author.json"
        }
    },
    "required": [
        "title",
        "author",
        "isbn"
    ]
}
```

and the author.json looks like this:

```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "author",
    "type": "object",
    "properties": {
        "firstName": {
            "description": "first name",
            "type": "string"
        },
        "lastName": {
            "description": "last name",
            "type": "string"
        }
    },
    "required": [
        "firstName",
        "lastName"
    ]
}
```

When I try to generate the service interface and model classes, I get this error:

```
[ERROR] Failed to execute goal org.raml.plugins:raml-jaxrs-maven-plugin:1.3.4:generate (default-cli) on project BookService: Error generating Java classes from: C:\Devel\JavaProjects\BookService\src\api\BookService.raml: Unrecognised URI, can't resolve this: file:/C:/Users/mydir/AppData/Local/Temp/1475181313344-0/author.json: C:\Users\mydir\AppData\Local\Temp\1475181313344-0\author.json (The system cannot find the file specified) -> [Help 1]
```

Can the plugin not resolve schemas that are referenced in separate files?

**Comment by idefixcert** [comment]
If you include both files:
```
schemas:
  - book:  !include book.json
  - author:  !include author.json
```

than you can reference like this:
`"$ref": "author"`

**Comment by vanDonselaar** [comment]
I think https://github.com/mulesoft/raml-for-jax-rs/issues/125 is related or even a duplicate.

**Comment by sdoca** [comment]
@idefixcert I updated the raml to include defining the author schema and then referencing that in the book.json and it correctly generated the model and resource classes/interface.  It's not intuitive that one could/should reference a raml schema in the json file, but it works!

Thanks!!!

@vanDonselaar I did see your issue when I was searching for a solution.  But, your workaround didn't work for me.  I had added creating an author schema in the raml, but since book.json still referenced author.json, I got the same error as before.

**Comment by jstoiko** [comment]
@sdoca I would be interested to know how your RAML and JSON schema files behave is the new 2.0.0 version? Would it be too much to ask you to try it and give your feedback here? The version is in a [separate branch](https://github.com/mulesoft-labs/raml-for-jax-rs/tree/release/2.0.0) for now.

**Comment by dcrossleyau** [comment]
Done some further exploration of this issue, using the head of master (1.3.5-SNAPSHOT) and release branch (2.0.0-RC2-SNAPSHOT).

The attached set of example files do "!include" a JSON schema file in another directory,
and that schema refers to another schema in a separate file.

The top-level schema examples use two different methods to declare the second JSON schema:

1) By filename -- "$ref": "pet.json"

2) By schema key -- "$ref" : "petSchema" (i.e. as declared in the top-level RAML file)

[pets.tar.gz](https://github.com/mulesoft-labs/raml-for-jax-rs/files/925121/pets.tar.gz)

```
test-pets/
|
|__ examples/
|   |__ valid-pet.json
|   |__ valid-pets.json
|
|__ ramls/
|   |__ 08-4-included-schema-filename.raml
|   |__ 08-5-included-schema-flat.raml
|   |__ 08-6-included-schema-key-id.raml
|   |__ 10-4-included-schema-filename.raml
|   |__ 10-5-included-schema-flat.raml
|   |__ 10-6-included-schema-key-id.raml
|
|__ schema/
    |__ pet.json
    |__ pets-filename.json (includes "pet" via "$ref": "pet.json")
    |__ pets-flat.json
    |__ pet-key-id.json
    |__ pets-key-id.json (includes "pet" via "$ref" : "petSchema")
```

Results:

The *-flat.raml examples of course are successful because the schema is self-contained.

Using 2.0.0-RC2-SNAPSHOT -- both referencing methods are successful for the RAML-0.8 files.

Using 2.0.0-RC2-SNAPSHOT -- both methods fail for the RAML-1.0 files.
`Exception in thread "main" org.raml.jaxrs.generator.GenerationException: [Error validating JSON. Error: Invalid json content ...`
This seems to be due to [raml-java-parser/issues/362](https://github.com/raml-org/raml-java-parser/issues/362).

Using 1.3.5-SNAPSHOT -- the "key" method is successful for the RAML-0.8 files.

Using 1.3.5-SNAPSHOT -- the "filename" method fails for the RAML-0.8 files.
`java.lang.IllegalArgumentException: Unrecognised URI, can't resolve this: file:/var/folders/cd/8xnly0xx3g78n701q76wj1l40000gp/T/1492398440074-0/pet.json`
However, note that at [raml-java-parser/issues/362](https://github.com/raml-org/raml-java-parser/issues/362) using the raml-parser v0.8.17 directly is successful.

**Comment by dcrossleyau** [comment]
That investigation shows that this issue also needs the "2.0.x" label.

**Comment by jpbelang** [comment]
I think #251 fixes this.
