### ISSUE TITLE
java.util.UUID with jaxrs-to-raml

### ISSUE THREAD

**Issue by derekm** [mulesoft-labs/raml-for-jax-rs#322]
How would I teach jaxrs-to-raml-cli about java.util.UUID types?

**Comment by jpbelang** [comment]
Does jackson2 handle UUID types natively ?  (I don't think so).

If it does (or if you can manage to register a serializer/deserializer outside of using annotations), you might be able to lie to it by forcing a java type on it with the className RAML annotation like this:
https://github.com/mulesoft-labs/raml-for-jax-rs/blob/821cc8864a690864e226a3465e49e27163fe8954/raml-to-jaxrs/jaxrs-code-generator/src/test/resources/org/raml/jaxrs/generator/v10/overrideScalarTypes.raml

Otherwise, you could write a plugin:
https://github.com/mulesoft-labs/raml-for-jax-rs/blob/master/raml-to-jaxrs/examples/maven-examples/features/README.md

**Comment by derekm** [comment]
I'm using jaxrs-to-raml... I want to generate RAML from my JAX-RS interfaces.

**Comment by jpbelang** [comment]
There is an example in the 3.0.0-SNAPSHOT that show you how to do this.
